productName = "Chromeless Viewer"
version = "1.0.0"
identifier = "com.chromeless.viewer"

[build]
frontendDist = "../dist"

[[app.windows]]
label = "main"
url = "index.html?url=https://copilot.microsoft.com/"
title = "Chromeless Viewer"
width = 1600
height = 900
resizable = true
decorations = true

[bundle]
active = false
icon = ["icons/icon.ico"]