[package]
productName = "Chromeless Viewer"
version = "1.0.0"
identifier = "com.chromeless.viewer"

[build]
devPath = "http://localhost:3000"
distDir = "../dist"

[tauri]
[tauri.windows]
label = "main"
title = "Chromeless Viewer"
width = 1600
height = 900
decorations = false
resizable = true

[tauri.security]
csp = ""

[tauri.bundle]
active = false  # disables installer generation
icon = ["icons/icon.ico"]  # optional, used for the .exe metadata

[tauri.updater]
active = false

[tauri.plugins]