productName = "Chromeless Viewer"
version = "1.0.0"
identifier = "com.chromeless.viewer"

[build]
frontendDist = "../dist"

[tauri.allowlist]
http = { all = true }

[[app.windows]]
label = "main"
title = "Chromeless Viewer"
width = 1600
height = 900
decorations = true
resizable = true

[bundle]
active = false
icon = ["icons/icon.ico"]

[plugins]
