productName = "Chromeless Viewer"
version = "1.0.0"
identifier = "com.chromeless.viewer"

[build]
# Remove or comment out devUrl
# devUrl = "http://localhost"

# Use the built frontend files
frontendDist = "../dist"

[[app.windows]]
label = "main"
title = "Chromeless Viewer"
width = 1600
height = 900
decorations = false
resizable = true

[bundle]
active = false
icon = ["icons/icon.ico"]

[plugins]
