productName = "Chromeless Viewer"
version = "1.0.0"
identifier = "com.chromeless.viewer"

[build]
devPath = "http://localhost:3000"
distDir = "../dist"

[app.windows]
label = "main"
title = "Chromeless Viewer"
width = 1600
height = 900
decorations = false
resizable = true

[bundle]
active = false
icon = ["icons/icon.ico"]

[plugins]