productName = "Chromeless Viewer"
version = "1.0.0"
identifier = "com.chromeless.viewer"

[build]
frontendDist = "../dist"
remove-unused-commands = true

[bundle]
active = false
icon = ["icons/icon.ico"]

[plugins]