[package]
name = "chromeless-viewer"
version = "1.0.0"
edition = "2021"

[dependencies]
tauri = { version = "1", features = ["api-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
crate-type = ["cdylib"]

[[bin]]
name = "chromeless-viewer"
path = "src/main.rs"