[package]
name = "chromeless-viewer"
version = "1.0.0"
edition = "2021"

[dependencies]
tauri = { version = "2", features = ["default"] }

[build-dependencies]
tauri-build = "2"

[[bin]]
name = "chromeless-viewer"
path = "src/main.rs"