[package]
name = "chromeless-viewer"
version = "1.0.0"
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "2", features = ["default"] }

[build-dependencies]
tauri-build = "2"

[[bin]]
name = "chromeless-viewer"
path = "src/main.rs"

[package.metadata.tauri]
config = "src-tauri/tauri.toml"