name: Build and Release Portable Tauri App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('src-tauri/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Extract MAJOR.MINOR from Cargo.toml
        id: version
        shell: pwsh
        run: |
          $content = Get-Content "src-tauri/Cargo.toml"
          $versionLine = $content | Where-Object { $_ -match '^version\s*=\s*".+"' }
          $version = ($versionLine -split '"')[1]
          $major_minor = ($version -split '\.')[0..1] -join '.'
          echo "major_minor=$major_minor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Update Rust Dependencies
        run: cargo update
        working-directory: src-tauri

      - name: Remove Cargo.lock to force fresh dependency resolution
        run: rm Cargo.lock
        working-directory: src-tauri

      - name: Build Tauri App
        run: cargo build --release
        working-directory: src-tauri

      - name: Create Git Tag with GitHub CLI
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          tag="v${{ steps.version.outputs.major_minor }}.${{ github.run_number }}"
          gh release create "$tag" --title "$tag" --notes "Automated release"

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.major_minor }}.${{ github.run_number }}
          name: Release v${{ steps.version.outputs.major_minor }}.${{ github.run_number }}
          body: |
            Automated release for version v${{ steps.version.outputs.major_minor }}.${{ github.run_number }}.
            Built and published by GitHub Actions.
          files: |
            src-tauri/target/release/chromeless-viewer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}