name: Build and Release Portable Tauri App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Rust Target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Clean Build Artifacts
        run: cargo clean

      - name: Cache Cargo Registry
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build Tauri App
        run: cargo tauri build -- --release
        working-directory: src-tauri

      - name: Upload EXE as GitHub Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: tauri-app-windows
          path: src-tauri/target/release/chromeless-viewer.exe