name: Build and Release Portable Tauri App

on:
  push:
    branches:
      - main
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache Cargo registry
        uses: actions/cache@v4.3.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Update Rust Dependencies
        run: cargo update

      - name: Remove Cargo.lock to force fresh dependency resolution
        run: rm Cargo.lock

      - name: Build Tauri App
        run: cargo build --release

      - name: Upload EXE as GitHub Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: tauri-app-windows
          path: src-tauri\target\release\chromeless-viewer.exe