name: Build and Release Portable Tauri App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust & Tauri CLI
        shell: pwsh
        run: |
          rustup update stable
          rustup default stable
          rustup target add x86_64-pc-windows-msvc
          cargo install tauri-cli

      - name: Build Windows EXE
        shell: pwsh
        run: |
          cargo tauri build -- --release

      - name: Upload EXE as GitHub Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: tauri-app-windows
          path: src-tauri/target/release/chromeless-viewer.exe